name: dart_many_parts
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.1
  string_scanner: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  path: ^1.8.3
